FROM python:3.6-slim

RUN mkdir /build

RUN pip3 install --upgrade pip && \
    pip3 install awscli boto3 pytest && \
    apt-get update && \
    apt-get install -y bash jq unzip zip

COPY lambda /build
COPY scripts/run_tests.sh /build

RUN chmod +x /build/run_tests.sh

WORKDIR /build

ENTRYPOINT ["/bin/bash", "./run_tests.sh"]
